### ISSUE TITLE
Classpath should use 'path.delimiter' (for Windows)

### ISSUE THREAD

**Issue by jc776** [dragos/dragos-vscode-scala#12]
On Windows, PATH and java -cp use a semicolon instead of a colon.
extension.ts: `"-cp", toolsJar + ":" + assemblyPath` should be `"-cp", toolsJar + path.delimiter + assemblyPath`.
(Unless you're doing the 'without tools.jar' version on ensime-vscode gitter)

I was able to get this running (before recent changes) with that change and unrelated changes to package.json/json-rpc, I'll try it with the new ones for a clean PR.

**Comment by dragos** [comment]
great, thanks!
