### ISSUE TITLE
Extension Marketplace

### ISSUE THREAD

**Issue by UserRandom** [dragos/dragos-vscode-scala#17]
Are you planning on publishing this extension to the VSCode extension marketplace? It is sorely lacking a useful Scala extension. In addition, publishing it may serve to generate additional contributors.

**Comment by dragos** [comment]
Yes, definitely. I wanted to iron out a few more issues before publishing, but you're right.. more contributors are always welcome. I'll try to get to it this weekend

**Comment by alexarchambault** [comment]
The server can be published on Sonatype / Central (like a standard library), then launched via the coursier launcher, like 'coursier launch com.github.dragos::ensime-server:0.1.0', rather than via an embedded assembly. I do that locally (after a publishLocal), it works just fine.

**Comment by dragos** [comment]
Thanks for the tip! I'll look into it.

**Comment by dragos** [comment]
@alexarchambault fixed the download size in #19 so I'm looking into publishing it now.

**Comment by dragos** [comment]
The extension [is live](https://marketplace.visualstudio.com/items?itemName=dragos.scala-lsp)! I didn't announce it yet, so please let me know if things work before I tweet.

**Comment by dragos** [comment]
Actually, it's not there just yet. Still need to figure out a way to publish my artifacts somewhere :)

**Comment by dragos** [comment]
Now it is, published to sonatype
