### ISSUE TITLE
Use proguard to decrease the download size

### ISSUE THREAD

**Issue by dragos** [dragos/dragos-vscode-scala#18]
The bundle is 62MB, but the Marketplace is limited at 30. We need proguard.

**Comment by jc776** [comment]
[Courser](https://github.com/alexarchambault/coursier)? "Bootstrap" makes a 12MB runnable thin-JAR that  downloads one or more Maven dependencies, then run your main class.
This would have to be a Maven package for releases, but test can use publishLocal.
I did try it (a replacement publishExtension task), but it didn't seem to react well to the logging libraries. I'll get an example tonight.

**Comment by alexarchambault** [comment]
You can even use straightaway its (currently ~12 kB) launcher, and call it like `java -noverify -jar /path/to/coursier-launcher launch com.github.dragos:ensimeServer_2.11:0.1.0` to spawn the server.

**Comment by dragos** [comment]
Thanks @jc776 and @alexarchambault, I will try out the launcher ASAP. I think @hedefalk mentioned some issues when using it in the Atom plugin, but I don't remember what they were. I'm assuming that when the file is already on disk there is no connection needed (so it would work well in offline mode)?

**Comment by jc776** [comment]
Yes - there's a cache in `~/.coursier` (much like `~/.ivy2`), and it looks there first for references: `./coursier launch org.clojure:clojure:1.7.0 -M clojure.main` worked for me with internet disabled.

```java -Dvscode.workspace=D:\Desktop\Projects\downloads\dragos-vscode-scala -jar coursier.jar launch com.github.dragos:ensimeServer_2.11:0.1.0-SNAPSHOT -r https://dl.bintray.com/dhpcs/maven -r https://oss.sonatype.org/content/repositories/snapshots``` gets far enough to start `pc.stdout.log` and `scala-langserver.log`, but it's producing [INFO] stdout as well.

`publishLocal` complains when overwriting if the version number isn't a SNAPSHOT.

**Comment by alexarchambault** [comment]
FYI, [this branch](https://github.com/alexarchambault/dragos-vscode-scala/tree/develop) uses coursier to launch the server. I can open PR for it if it looks fine.

**Comment by dragos** [comment]
Closing this issue as #19 fixed it in a much nicer way.

**Comment by hedefalk** [comment]
@dragos I think my issue was with the binary, not the jar. I think. Hard to remember :)
