### ISSUE TITLE
Details page on VS Code should inform about compatibility to other known plugins.

### ISSUE THREAD

**Issue by avalonx** [dragos/dragos-vscode-scala#22]
I suggest putting some suggestions or instructions as to what other known Scala plugins should/shouldn't be used with your plugin for compatibility reasons and best use combinations if any.

**Comment by dragos** [comment]
Did you notice any such incompatibilities? I am not sure what other Scala plugins there are and if there is any problem with them. If you notice anything, please contribute.

**Comment by jvican** [comment]
This was opened a long time ago... So far, I'm using the plugin with several vscode plugins and I have no issue. I suggest closing and to reopen if @avalonx is able to provide more information.

**Comment by dragos** [comment]
Yeah, good idea.
