### ISSUE TITLE
Scala server won't start

### ISSUE THREAD

**Issue by lolgab** [dragos/dragos-vscode-scala#23]
Tried in different scala projects but scala server doesn't work. (scala 2.11.8)
[ensime-langserver.log.txt](https://github.com/dragos/dragos-vscode-scala/files/828280/ensime-langserver.log.txt)

**Comment by dragos** [comment]
That looks bad, but the log doesn't say much more than that the Ensime actor system got shut down because of a fatal error:

```
[2017-03-08 17:39:20,441] ERROR akka.actor.ActorSystemImpl - Uncaught fatal error from thread [ENSIME-akka.actor.default-dispatcher-4] shutting down ActorSystem [ENSIME]
[2017-03-08 17:39:20,522] ERROR akka.actor.ActorSystemImpl - Uncaught fatal error from thread [ENSIME-akka.actor.default-dispatcher-2] shutting down ActorSystem [ENSIME]
```

Can you try using Ensime 2.0? Have a look at the ensime [sbt docs]( http://ensime.org/build_tools/sbt/), it should be as simple as adding

```
import org.ensime.EnsimeCoursierKeys._
ensimeServerVersion in ThisBuild := "2.0.0-SNAPSHOT"
```

to your build.

**Comment by alexarchambault** [comment]
FYI I've been running into similar errors when the `JAVA_HOME` env var wasn't set (which makes `tools.jar` not land in the classpath, see around [here](https://github.com/dragos/dragos-vscode-scala/blob/86ebc3aa6a270ebdced552bb5f2f61a7aeec0033/scala/src/extension.ts#L11)).

Maybe the java home detection could be made a bit more portable (e.g. by calling `/usr/libexec/java_home` on OS X).

**Comment by k--kato** [comment]
vscode-java
Setting the JDK, https://github.com/redhat-developer/vscode-java#setting-the-jdk

**Comment by dragos** [comment]
Good point @alexarchambault, can you double-check that? And yes, we should have better logic for finding `tools.jar`. I'll file a ticket

**Comment by alexarchambault** [comment]
It's documented [here](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/java_home.1.html) for example. On my machine, I get
```
$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home
```

**Comment by dragos** [comment]
@lolgab would you be able to try out `master`? There's a fix in #24 that might solve the issue for you.

**Comment by lolgab** [comment]
@dragos I compiled following your instruction on README and installation seems ok, but no messages and no ensime-langserver.log.txt being created...  Seems that the server doesn't start..
I tried to set JAVA_HOME before trying the master version using the one from the store and I had the same errors as before...

**Comment by lolgab** [comment]
Is there a way to have from vscode some debug information from the extentions?

**Comment by dragos** [comment]
You can have some (not much) debugging output showing in the javascript console. Help -> Toggle Developer Tools.

**Comment by lolgab** [comment]
I tryed now to debug the extension (opening dragos-vscode-scala/scala in vscode and pressing F5 )and it works nicely now :-) 
The developer tools gives me this error:
[Extension Host] L'attivazione dell'estensione `dragos.scala-lsp` non è riuscita: Cannot find module 'path-exists'.
[Extension Host] Activating extension `dragos.scala-lsp` failed:  Cannot find module 'path-exists'
[Extension Host] Here is the error stack:  Error: Cannot find module 'path-exists'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:15:19227)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lorenzo/.vscode/extensions/dragos.scala-lsp-0.1.2/out/src/requirements.js:11:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
L'attivazione dell'estensione `dragos.scala-lsp` non è riuscita: Cannot find module 'path-exists'.

**Comment by dragos** [comment]
@k--kato maybe can help? Normally the `npm install` step should have downloaded all dependencies. It's interesting that it works though.

When it doesn't work, do you see a line like this in your Developer Tools Window?

```
browser/workbench.main.js:136 [Extension Host] Adding to classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/lib/tools.jar
```

**Comment by k--kato** [comment]
@dragos maybe I wrote `path-exists` at `devDependencies` in `package.json`. So, we (developers) can run normally, but users can't, I think. @lolgab would you be able to try `fixed release dependencies #26`?

**Comment by lolgab** [comment]
@k--kato tryed just now and IT works :-)
The vsix generated file passed from ~100 kB to 1.3Mb :-D So some dependencies were not in the package i think :-) 
Now All works nicely ;-)

**Comment by dragos** [comment]
Great, thanks @k--kato for the fix and @lolgab for trying it out. I'll merge the change and publish a new release

**Comment by lolgab** [comment]
Thanks for your great work :-)

**Comment by dragos** [comment]
👍 

Release 0.1.3 is out.
