### ISSUE TITLE
ensimeConfig not a valid command.

### ISSUE THREAD

**Issue by ibnuda** [dragos/dragos-vscode-scala#27]
I'm using this extension in a scalatra project on windows 10.

VSCode tells me that I can generate .ensime using `sbt ensimeConfig` command.  And here's the screencap.
![problem](https://cloud.githubusercontent.com/assets/8169908/23835089/961e2c78-0793-11e7-9c5e-c5d69c677126.PNG)

**Comment by ibnuda** [comment]
Sorry, it's my fault. I need to sleep.
I haven't installed sbt.

**Comment by dragos** [comment]
You need the sbt-ensime plugin. Please follow http://ensime.org/build_tools/sbt/
