### ISSUE TITLE
Error downloading coursier under a proxy

### ISSUE THREAD

**Issue by fede0664** [dragos/dragos-vscode-scala#29]
Error while downloading https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier-cli_2.11/1.0.0-M15/coursier-cli_2.11-1.0.0-M15-standalone.jar: Connection refused: connect, ignoring it

**Comment by dragos** [comment]
@alexarchambault do you know how we could fix this? At first glance, I didn't find anything on google on how to make it work :)

**Comment by alexarchambault** [comment]
Yeah, coursier uses standard `HttpUrlConnection`s, so it's just a matter of setting the right Java properties (described [here](http://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html)) when [launching coursier](https://github.com/dragos/dragos-vscode-scala/blob/8d99eefdf2f82fc0aa40f913c75aa5ee7195e64d/scala/src/extension.ts#L37).
