### ISSUE TITLE
Make note in readme for anyone using jenv

### ISSUE THREAD

**Issue by jmparsons** [dragos/dragos-vscode-scala#32]
My installation was pointing to the wrong location for picking up `tools.jar`.

Evidently my `JDK_HOME` and `JAVA_HOME` weren't set by [jenv](http://www.jenv.be/).

Running this worked for me:

```bash
jenv enable-plugin export
```

Fixing the location in dev tools from:

```bash
.jenv/lib/tools.jar
```

To:

```bash
.jenv/versions/1.8/lib/tools.jar
```

 https://github.com/gcuisinier/jenv/issues/44.

**Comment by jvican** [comment]
I wonder, is this really a problem of this plugin and not your ensime configuration? It's ensime, after all, who tells the ensime server the jars that should be used. I think this plugin has nothing to do with this...

**Comment by jmparsons** [comment]
@jvican I upgraded my sbt and project and had better results. This was a side case issue just going to close it out.
