### ISSUE TITLE
Infix notation for method invocation reports error

### ISSUE THREAD

**Issue by AesaKamar** [dragos/dragos-vscode-scala#41]
In both error cases, it reports:
`value :: is not a member of Int`

<img width="390" alt="screen shot 2017-04-28 at 4 40 49 pm" src="https://cloud.githubusercontent.com/assets/4334491/25546526/79063410-2c31-11e7-962b-d109aabb3ae8.png">

**Comment by dragos** [comment]
Actually, the error is correct. Methods that end with `:` are right-associative when used in infix notation. So, what you're trying to do should be `2 :: x`. `::` is actually prepending, so the notation is more natural ("2" in front of "x").

**Comment by AesaKamar** [comment]
My mistake, thanks for the prompt clarification~
