### ISSUE TITLE
FEAT Request: Add automatic Scala format support post saving .scala source code

### ISSUE THREAD

**Issue by kggp1995** [dragos/dragos-vscode-scala#43]
Can we push this feature of using sbt and ensime to automatically format the scala code with indentations, space etc..?
Thanks in Advance.
Keep up the GR8 work!!!

**Comment by kggp1995** [comment]
UPDATE: I have found the sbt "scalafmt" plugin to be helpful. Willing to integrate it if guidance is provided :)

**Comment by dragos** [comment]
Thanks @kggp1995 for the offer! Absolutely, it would be great! There are a few steps to add a new feature:

- modify the language server library to add support for [formatting](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_formatting)
- add the feature in ensime-lsp
  - add the feature in the "connect" response message
  - implement the format method, delegate to scalafix, return the `TextEdits` necessary to format the document -- here it depends on how scalafix works, and if it can produce text edits, or just full document formatting

Let me know if you have issues with any of these steps.. You can have a look at how hover works, it should have all of the steps above.

**Comment by kggp1995** [comment]
Thanks for the brief, @dragos ! Will look into it!

**Comment by kggp1995** [comment]
@dragos , ENSIME mentions in their site that it recommends the use of "scalaiform". We know that the Typesafe Scala IDE uses the same dependency as well.
In the ensime sbt shell, the scalaiform performs automatic formatting "ON COMPILE / RUN" by adding this to the build.sbt:

`resolvers += Resolver.typesafeRepo("releases")

addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.6.0")
`

**Any chance of integrating the scalaiform feature within this plugin?**

Keen on hearing :)

**Comment by dragos** [comment]
I'm not sure if you're suggesting to add a new sbt task? Sure, go ahead!

I think scalariform is perfectly fine as a formatting tool. It would still be nice to have editor integration, without a round-trip through Sbt. That allows format-selection instead of the whole project, etc.

**Comment by kggp1995** [comment]
Yes, sure!
So, we can now add config for the new command `sbt: scalariformFormat` in  dragos-vscode-scala/scala/package.json. _Anywhere else the config must be reflected?_

_Also wondering how to ensure the scalaiForm plugin be added to the VS Code projects..
Could you assist on that?_

**Comment by kggp1995** [comment]
This is now addressed. Thanks for your support!

#44

**Comment by kggp1995** [comment]
Reopen: Will be closed after PR #44 is merged into the master

**Comment by kggp1995** [comment]
#44 merged
