### ISSUE TITLE
Improve README to describe the Ensime relationship

### ISSUE THREAD

**Issue by huntc** [dragos/dragos-vscode-scala#53]
I think that the README could be improved to explain the relationship to Ensime. Ensime is new to me, and I found myself wondering at what point do I need to add the sbt plugin and when do I need to invoke the `ensimeConfig` command. I'd be happy to raise a PR once I understand these two things at least. :-)

**Comment by dragos** [comment]
I know this is confusing, but in fact, there are two READMEs: the root one, and the VS Code-specific one, [here](https://github.com/dragos/dragos-vscode-scala/tree/master/scala). Unfortunately, only that one ends up on the VS marketplace, and that's what users see. Perhaps there's some clever tweaks to the vspublish tool that I could make, but for the moment I'm stuck with these two. Is the "user-facing" README still unclear on how we use Ensime?

**Comment by huntc** [comment]
Perhaps a few words introducing Ensime might help. I've never used it or bothered to find out more until now. I'll take a stab at a PR.

**Comment by huntc** [comment]
Btw I still don't understand when I need to manually invoke `ensimeConfig`...
