### ISSUE TITLE
High memory footprint

### ISSUE THREAD

**Issue by mgobec** [dragos/dragos-vscode-scala#55]
Hi,

I setup the latest release of this VS Code plugin through extensions tab (awesome work) when VS Code starts it spawns two java processes one consuming ~4.5GB and another ~500mb or memory.

VS Code version: Version 1.16.0 (1.16.0)
SBT version in project: sbt.version=0.13.15
Scala version in project: scalaVersion := "2.11.8"
Ensime plugin version: addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.0")

Thanks,
Matija

**Comment by dragos** [comment]
Indeed, it looks like the default Coursier JVM process runs with a 4G heap, and currently there is no way to change that. See https://github.com/coursier/coursier/issues/357

**Comment by mgobec** [comment]
I'll keep an eye on that issue then and close this one.
Btw, the plugin works great. Thank Iulian.

**Comment by alexarchambault** [comment]
@dragos The amount of memory can be changed from here, as we're launching coursier via a custom java command. E.g. `-Xmx` etc. options could be added around [here](https://github.com/dragos/dragos-vscode-scala/blob/master/scala/src/extension.ts#L53).

**Comment by mgobec** [comment]
@alexarchambault Good one. Lets keep it active then 👍

**Comment by dragos** [comment]
Fixed in the latest release.
