### ISSUE TITLE
Sept 19 0.2.0 update causes errors

### ISSUE THREAD

**Issue by yelled1** [dragos/dragos-vscode-scala#59]
I think VSCode decided to do an auto update
Don't know why, but I got an "extension host terminated unexpectedly error"
and OUTPUT terminal below shows it's trying to access ensime as 2.12 (Scala I believe)
I still have 2.11.8 because of Spark. Emacs ensime works, but not VSCode.
I have ubuntu 16.04 64bit 4.4.0-96-generic kernel.
cat build.sbt 
```
name := course.value + "-" + assignment.value

scalaVersion := "**2.11.8**"

scalacOptions ++= Seq("-deprecation")

// grading libraries
libraryDependencies += "junit" % "junit" % "4.10" % "test"

// for funsets
libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "1.0.4"

// include the common dir
commonSourcePackages += "common"

courseId := "BRPX"

// See documentation in ProgFunBuild.scala
assignmentsMap := {
  val styleSheetPath = (baseDirectory.value / ".." / ".." / "project" / "scalastyle_config.xml").getPath
  Map(
    "example" -> Assignment(
      packageName = "example",
      key = "g4unnjZBEeWj7SIAC5PFxA",

```
cat project/build.properties 
`sbt.version=0.13.15`

Downloading https://repo1.maven.org/maven2/com/github/dragos/ensime-lsp_2.12/0.2.0/ensime-lsp_2.12-0.2.0.pom
Downloading https://repo1.maven.org/maven2/com/github/dragos/ensime-lsp_2.12/0.2.0/ensime-lsp_2.12-0.2.0.pom.sha1
Downloading https://dl.bintray.com/dhpcs/maven/com/github/dragos/ensime-lsp_2.12/0.2.0/ensime-lsp_2.12-0.2.0.pom
Downloading https://dl.bintray.com/dhpcs/maven/com/github/dragos/ensime-lsp_2.12/0.2.0/ensime-lsp_2.12-0.2.0.pom.sha1
Downloading https://oss.sonatype.org/content/repositories/releases/com/github/dragos/ensime-lsp_2.12/0.2.0/ensime-lsp_2.12-0.2.0.pom
Downloading https://oss.sonatype.org/content/repositories/releases/com/github/dragos/ensime-lsp_2.12/0.2.0/ensime-lsp_2.12-0.2.0.pom.sha1

Error:
  com.github.dragos:ensime-lsp_2.12:0.2.0:
    not found: /home/userName/.ivy2/local/com.github.dragos/ensime-lsp_2.12/0.2.0/ivys/ivy.xml
    not found:

**Comment by GoranSchumacher** [comment]
I am also getting the same issue although it is just with a standard project

**Comment by mdedetrich** [comment]
Getting this error too, its not finding a proper package in maven repo?

**Comment by gotoeveryone** [comment]
I am having the same problem. I have built and used 0.1.6.

**Comment by dragos** [comment]
Sorry, the last step (promoting the release) has failed and I didn't notice. It all worked fine locally because I had the binaries in my local cache. Now everything should be back to normal.

**Comment by yelled1** [comment]
Working now :+1:

**Comment by mdedetrich** [comment]
Thanks for fixing this, its now working!
