### ISSUE TITLE
LanguageServer component as a separate library

### ISSUE THREAD

**Issue by keyboardDrummer** [dragos/dragos-vscode-scala#79]
Hi,

Could you move everything in "/languageserver/src" into a separate library? I know the code hasn't been written to be a library, but it's generic enough to be re-usable. Currently I'm just copy pasting your code for adding LSP support to [Miksilo](https://github.com/keyboardDrummer/Miksilo).

Cheers,
Remy

**Comment by alexarchambault** [comment]
@keyboardDrummer It's already published as a library (`"com.github.dragos" %% "languageserver" % "0.2.1"`, for scala 2.12). The extension here fetches it [this way](https://github.com/dragos/dragos-vscode-scala/blob/41939453d8efa2ee020bc37236d04fc2b4f7d553/scala/src/extension.ts#L56) (via the `ensime-lsp` module, published as a library too).

**Comment by dragos** [comment]
Thanks @alexarchambault, I think that's should be good enough for now.
